# Site
name: "Risk-First"
title: "Risk-First Software Development"
description: "Home of Risk-First Software Development" 
logo: 'images/r1_logo_round_black.png'
favicon: favicon.ico
author: risk_first
page_lang: en-GB
permalink: /:categories/:year/:month/:day/:title

category_list: 
  - Front
  - Introduction
  - Risks
  - Thinking Risk-First
  - Practices
  - Methods
  - News
  - Estimating
  - Complexity

# Authors
authors:
  rob:
    name: risk_first
    display_name: Rob Moffat
    gravatar: 29de34339da3e024b8e6974b05c74530
    email: rob@kite9.com
    web: https://robmoff.at
    twitter: "@risk_first"
    description: |
      Author of Risk-First Software Development. 
      Developer. Working in the UK.  

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-relative-links
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Twitter  
twitter:
  username: risk_first
  card: summary_large_image
  title: Risk-First Software Development 

# Post Defaults
defaults:
  - scope:
      path: ""
    values:
      author: rob
      layout: post
      categories: [Post]

# Analytics
webmaster_verifications:
  google: _Ah_sAWlHVd7-glADdzxCZLqt-HDlhCXLlMqlQGqLE4
  bing: 9DFE22A35BB1805E3474C158DC853AB4
  
# Markup
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      
relative_links:
  enabled:     true
  collections: true